[tasks.copy-debug]
dependencies = ["build"]
script = '''
cp -f ./target/x86_64-unknown-none/debug/kernel ../mock/EFI/lotus/bud
'''
# Copy-Item -Force ".\\target\\x86_64-unknown-none\\debug\\kernel" "..\\mock\\EFI\\lotus\\bud"
# script_extension = "ps1"
# script_runner = "powershell"
script_extension = "sh"
script_runner = "bash"

[tasks.copy-release]
dependencies = ["build-release"]
script = '''
cp -f ./target/x86_64-unknown-none/release/kernel ../mock/EFI/lotus/bud
'''
# Copy-Item -Force ".\\target\\x86_64-unknown-none\\release\\kernel" "..\\mock\\EFI\\lotus\\bud"
# script_extension = "ps1"
# script_runner = "powershell"
script_extension = "sh"
script_runner = "bash"

[tasks.qemu-debug]
args = [
  "-m",
  "1024",
  "-bios",
  "/usr/share/edk2/ovmf/OVMF_CODE.fd",
  "-nodefaults",
  "-display", 
  "gtk",
  "-vga",
  "std",
  "-drive",
  "file=fat:rw:../mock,media=disk,format=raw",
  "-serial",
  "mon:stdio",
  "-no-reboot",
  "-no-shutdown",
  "-nographic",
  "-d",
  "int",
  "-D",
  "log",
  "-M",
  "smm=off",
]
command = "qemu-system-x86_64"
dependencies = ["copy-debug"]

[tasks.qemu-debug-gdb]
args = [
  "-m",
  "1024",
  "-bios",
  "/usr/share/edk2/ovmf/OVMF_CODE.fd",
  "-nodefaults",
  "-display", 
  "gtk",
  "-vga",
  "std",
  "-drive",
  "file=fat:rw:../mock,media=disk,format=raw",
  "-serial",
  "mon:stdio",
  "-no-reboot",
  "-no-shutdown",
  "-nographic",
  "-d",
  "int",
  "-D",
  "log",
  "-M",
  "smm=off",
  "-s",
  "-S",
]
command = "qemu-system-x86_64"
dependencies = ["copy-debug"]

[tasks.qemu-release]
args = [
  "-m",
  "1024",
  "-bios",
  "/usr/share/edk2/ovmf/OVMF_CODE.fd",
  "-nodefaults",
  "-display", 
  "gtk",
  "-vga",
  "std",
  "-drive",
  "file=fat:rw:../mock,media=disk,format=raw",
  "-serial",
  "mon:stdio",
  "-no-reboot",
  "-no-shutdown",
  "-nographic",
  "-d",
  "int",
  "-D",
  "log",
  "-M",
  "smm=off",
]
command = "qemu-system-x86_64"
dependencies = ["copy-release"]

[tasks.qemu-release-gdb]
args = [
  "-m",
  "1024",
  "-bios",
  "/usr/share/edk2/ovmf/OVMF_CODE.fd",
  "-nodefaults",
  "-display", 
  "gtk",
  "-vga",
  "std",
  "-drive",
  "file=fat:rw:../mock,media=disk,format=raw",
  "-serial",
  "mon:stdio",
  "-no-reboot",
  "-no-shutdown",
  "-nographic",
  "-d",
  "int",
  "-D",
  "log",
  "-M",
  "smm=off",
  "-s",
  "-S",
]
command = "qemu-system-x86_64"
dependencies = ["copy-release"]
